### ISSUE TITLE
data

### ISSUE THREAD

**Issue by 3545652134** [spaceml-org/karman#1]
During use, it only displays data for the 32nd day of 2004. Is it necessary to download additional data sources?

**Comment by Sceki** [comment]
Yes: it is necessary to download and prepare the data from several sources (i.e., http://thermosphere.tudelft.nl/, https://celestrak.com/SpaceData/, https://kp.gfz-potsdam.de/en/data, and https://omniweb.gsfc.nasa.gov/ow.html).. soon, however, we plan to release the scripts to use for preparing and downloading these data

**Comment by Sceki** [comment]
@3545652134 Closing this as there are now scripts to download, process, and merge the data. Sorry for the delay :)

You can find the scripts in `scripts/input_data_prep`. A brief description of how to run them is here: https://spaceml-org.github.io/karman/tutorials.html

**Comment by 3545652134** [comment]
Thank you for your data support. I will try to use it in my scientific research. Thank you.
